name: Scientific research in 100 different bases

on:100 sites for scientific research in various fields from the open source directory for Arab journalists
 http://education.iseek.com/iseek/home.page
It is an excellent engine for research and is aimed at students and educators. It has many reliable research sources and thus saves you more time and effort.
http://www.refseek.com/
It contains more than 1 billion documented files between web pages, books, magazines, newspapers and more. You can get reliable sources on any topic and avoid any chaos or the appearance of sponsored links.
 http://www.virtuallrc.com/
The site includes the best sites for academic information. It is designed by educators and professionals around the world to share plenty of resources on different research topics.
http://bubl.ac.uk/link/
The site can search by keywords and browse many sites and documented sources.
 http://dlc.dlib.indiana.edu/dlc
You can search on world literature and access a different set of full text articles and theses.
 http://www.oclc.org/oaister/
The engine allows searching in the database and finding millions of digital resources and access to open sources.
http://www.ipl.org/div/subject/
You can search for resources on different topics through the online public library database.
 http://infomine.ucr.edu/
One of the search engines that enables you to find a wide range of scientific sources, especially in the field of science.
 http://academic.research.microsoft.com/
Microsoft's search engine provides access to more than 38 million different publications, whether maps or graphs, and many books by authors.
 http://www.google.com/trends/correlate/
It is a more than wonderful search engine that allows you to get a different set of real data.
 http://www.wolframalpha.com/tour/examples.html
It is not only a search engine for different links, but it answers various questions and many reports.
http://www.google.com/educators/p_booksearch.html
It allows Internet users to search for thousands of books and browse these books that help you achieve your educational goals.
Search engines that show many results at once:
 http://www.dogpile.com/
The engine gives a set of different results, whether from Google, Yahoo, Bing and also different categories of sites, images, videos, books.
 http://www.metacrawler.com/
The engine knows search results from Google, Yahoo, Bing.
 http://www.mamma.com/
The engine displays the best resources on the Internet. Even if you are looking for a job online.
Databases and Documentation Engines:
 http://www.loc.gov/index.html
This library contains an incredible amount of different sources, books, historical photos, digital collections.
 http://archiveshub.ac.uk/index.html
You can get the best British documents from nearly 200 institutions that put their sources on the site.
http://www.archives.gov/research/search/
It enables the public to access a range of historical documents, research and government information.
 http://arxiv.org/
The engine makes it possible to find a wealth of electronic publications in mathematics, science, and subjects in various fields. You can search for what you need between 756,133 documents.
 http://www.archiefnet.nl/index.asp?taal=en
The engine makes it easy to find Indian documents.
 http://www.ksc.nasa.gov/inforcenter/history/history.html
The engine is characterized by the ability to search for space research, space history and various missions.
 http://www.nal.usda.gov/
This engine is offered as a service of the US Department of Agriculture, where you can find a huge collection of global agricultural information in the National Agricultural Library.
 http://www.siris.si.edu/
The Smithsonian provides an engine for information and research, because it's a great way to search for more than 7.4 million records on museums, archives, books, and libraries.
 http://www.bl.uk/indexmenuonly.shtml#tabcollns
The engine helps you explore British catalogs, print materials, digital collections, and is a wealth of trusted sources.
 https://www.cia.gov/
The Central Intelligence Center has compiled a collection of books on world facts and provides key reference information around the world. It covers more areas published online.
 http://www.ncsl.org/
You can use this site to access a database of the legislative bodies of all US states.
 http://www.opendoar.org/search.php
The engine is an open directory for searching various academic research information and accessing reliable sources of interest.
 http://catalog.gpo.gov/F?RN=217638743
The engine is a searchable catalog of historical publications and direct links.
 http://www.worldcat.org/
You can find nearly 10,000 libraries around the world and view books, DVDs, CDs, and articles in a global index.
 http://books.google.com/
One of the tools to search for millions of books around the world and many more books to preview.
http://www.scirus.com/
This comprehensive search engine performs over 410 million scholarly articles including journals, courseware, patents, educational websites, and more.
 http://www.highbeam.com/
The site contains sources, research, articles and a selection of research materials and various topics.
 http://vadlo.com/
A search engine for different life sciences, providing protocols and tools, and discovering more useful sources for scientific research.
 http://openlibrary.org/
The engine is very suitable for searching classic literature, accessing open e-books, and sharing books.
 http://www.ojose.com/
The site is distinguished by the discovery of magazines and reports
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: shehata el-sayed
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://www.facebook.com/oshsource/?ref=pages_you_manage

    # - name: Run test suite
    #   run: composer run-script test
